# Author: Matteo Rondini - Version 1.00
# Changes the structure of data inside the lines of a source txt file, 
# generated by an hardware barcode scanner, into an AS400 readable file.
# ie: from "     80038238000000400", to "0000180038238     000400"

originale = []  # Declares host lists
finale = []

print("Converte PCINVENT.001 (logged) in TERMLIST.txt\nAutore: Matteo Rondini")

with open("PCINVENT.001", "r") as file:  # Reads logged PCINVENT file
    for line in file:
        originale.append(line)

for s in originale:  # Populating destination list
    conta_sp = str.count(s, " ")
    finale.append("00001" + s[0 + conta_sp : 13 :] + " " * conta_sp + s[16::])

with open("TERMLIST.TXT", "w") as file:  # Writes list content inside TERMLIST.TXT
    for elemento in finale:
        file.write(elemento)
